In [1]:
import os

In [2]:
os.chdir("C:\\Users\\Prasa\\OneDrive\\Documents")

## import essential libraries

In [35]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("Crop_recommendation.csv")

In [5]:
df.head()

N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [6]:
df.shape

(2200, 8)

In [7]:
df.describe()

N            P            K  temperature     humidity  \
count  2200.000000  2200.000000  2200.000000  2200.000000  2200.000000   
mean     50.551818    53.362727    48.149091    25.616244    71.481779   
std      36.917334    32.985883    50.647931     5.063749    22.263812   
min       0.000000     5.000000     5.000000     8.825675    14.258040   
25%      21.000000    28.000000    20.000000    22.769375    60.261953   
50%      37.000000    51.000000    32.000000    25.598693    80.473146   
75%      84.250000    68.000000    49.000000    28.561654    89.948771   
max     140.000000   145.000000   205.000000    43.675493    99.981876   

                ph     rainfall  
count  2200.000000  2200.000000  
mean      6.469480   103.463655  
std       0.773938    54.958389  
min       3.504752    20.211267  
25%       5.971693    64.551686  
50%       6.425045    94.867624  
75%       6.923643   124.267508  
max       9.935091   298.560117

In [8]:
df.label.value_counts()

lentil         100
mungbean       100
pomegranate    100
chickpea       100
jute           100
muskmelon      100
apple          100
rice           100
mango          100
watermelon     100
banana         100
blackgram      100
papaya         100
coffee         100
orange         100
coconut        100
pigeonpeas     100
maize          100
mothbeans      100
cotton         100
grapes         100
kidneybeans    100
Name: label, dtype: int64

In [9]:
df.isna().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [10]:
df

N   P   K  temperature   humidity        ph    rainfall   label
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...   ...  ..  ..          ...        ...       ...         ...     ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[2200 rows x 8 columns]

## spliting data as features and targets...

In [11]:
x = df.drop("label", axis= "columns")

In [12]:
y = df.label

## cross_val_score gives the scores for every algorithms.
## so that, we can use right algorithm for our model.

In [13]:
from sklearn.model_selection import cross_val_score

### Logistic regression :

In [14]:
from sklearn.linear_model import LogisticRegression
cross_val_score(LogisticRegression(),x,y)


C:\Users\Prasa\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Prasa\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

array([0.95      , 0.96590909, 0.94772727, 0.96590909, 0.94318182])

### Decision tree classifier :

In [15]:
from sklearn.tree import DecisionTreeClassifier
cross_val_score(DecisionTreeClassifier(),x,y)


array([0.98863636, 0.98409091, 0.99090909, 0.99318182, 0.98409091])

### Support vector machine :

In [16]:
from sklearn.svm import SVC
cross_val_score(SVC(),x,y)


array([0.98409091, 0.97954545, 0.97954545, 0.97272727, 0.975     ])

### Random forest classifier :

In [17]:
from sklearn.ensemble import RandomForestClassifier
cross_val_score(RandomForestClassifier(),x,y)


array([0.99772727, 0.99090909, 0.99772727, 0.99318182, 0.98636364])

### Training the model : 

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [20]:
len(x_train)

1760

In [21]:
len(x_test)

440

In [22]:
from sklearn.ensemble import RandomForestClassifier

In [23]:
model = RandomForestClassifier()

In [36]:
model.fit(x,y)

RandomForestClassifier()

In [25]:
model.score(x_train,y_train)

1.0

### Testing the model :

In [26]:
model.score(x_test,y_test)

1.0

In [27]:
df.head(3)

N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice

In [28]:
df.tail()

N   P   K  temperature   humidity        ph    rainfall   label
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

## predicting our model with different values.

In [29]:
model.predict([[60,55,44,23,82,7,263]])[0]

C:\Users\Prasa\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


'rice'

In [30]:
model.predict([[70,61,46,73,98,4,200]])[0]

C:\Users\Prasa\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


'papaya'

In [31]:
model.predict([[104,18,30,23,60,6,140]])[0]

C:\Users\Prasa\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


'coffee'

In [32]:
model.predict([[10,34,54,45,56,7,234]])[0]

C:\Users\Prasa\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


'mango'

## pickle module 

In [33]:
import pickle

## dump() function is used to store the object data to the file.

In [34]:
with open('crop_recommendation.pkl','wb') as f:
    pickle.dump(model,f)